### ISSUE TITLE
本地测试部署问题

### ISSUE THREAD

**Issue by wansho** [hangbale/photography-blog#1]
<img width="1906" alt="image" src="https://user-images.githubusercontent.com/28779244/174203556-bb94bd6d-fb80-47cd-b22f-b884fa5b34a9.png">

本地测试部署是这样的，不知道什么原因

**Comment by doom40k** [comment]
网站根目录应该是public

**Comment by wansho** [comment]
> 

没错呀，是 public

**Comment by doom40k** [comment]
那应该访问 127.0.0.1:5500就行了，不需要在url后面加/public/index.html

**Comment by wansho** [comment]
> 那应该访问 127.0.0.1:5500就行了，不需要在url后面加/public/index.html

好了，部署到服务器上就可以了，本地用的 vscode 中的 live server 插件测试的，有点问题

感谢！
