### ISSUE TITLE
关于生成public目录的询问

### ISSUE THREAD

**Issue by real-jiakai** [hangbale/photography-blog#2]
博主，这个项目是基于rust语言的。我在windows电脑上看网上的教程安装好了rust。
输入`rustc --version`命令能显示出rust版本。
生成public目录的命令`./blog-cli`，我在powershell、git bash、cmd中都试过了，无法执行这个可执行文件，这需要什么条件？我该如何操作，需要学习一些什么知识才能生成public目录?
期待您的回复。

**Comment by doom40k** [comment]
额 我忘记说明了😂
这个可执行文件是我在mac下编译的
windows的话可以自己编译一份: 删掉这个可执行文件 然后在项目根目录执行 cargo build --release就行了，cargo源可以换成国内的，不然包下载很慢

**Comment by real-jiakai** [comment]
再次询问，执行了`cargo build --release`命令后，在项目根目录下生成了一个target文件夹，里面的release文件夹里面有可执行文件blog-cli.exe，我将其复制到项目的根目录，双击后，生成了public文件夹，里面就一个index.html，和我的一个图片合集文件夹，在图片合集文件夹里面也仅有一个index.html。
目录结构是这样的：
public
├── index.html
└── 旅游
    └── index.html
我看第一个发起issue的大哥是部署在vercel上的，于是我也准备将其部署在vercel上。但是我设置了项目根目录为public后，vercel部署完，界面就是和第一个发起isssue的大哥的本地效果一样。检查控制台，发现一堆静态资源404。

后来，我将image文件夹以及template文件夹里面的assets文件夹复制到了public文件夹，然后将项目根目录设置为public，vercel才正常显示。
请问大哥，是不是运行了blog-cli还需要手动复制image文件夹以及assets文件夹啊？还是我环境的问题？即环境正常，运行blog-cli就自动复制了上述文件夹至public文件夹中？

**Comment by doom40k** [comment]
因为我写的时候没有考虑到兼容windows的情况，复制文件用了shell command，
Windows不支持，所以没有自动复制
等下我打个补丁改成std api的方式

**Comment by real-jiakai** [comment]
现在能正常使用，改了template文件夹下面的index.html，还得再次双击blog-cli.exe，以更新页面的配置。
如baidu的script标签、about的链接修改、icon-album图标注释掉了，需更新页面配置。
总体而言 ，这个项目不错。上个月就star了。昨天心血来潮，去tg群里面翻了老半天的历史记录，才找到这个项目。
感谢作者！❤️❤️❤️

**Comment by doom40k** [comment]
因为生成的都是静态文件，Template 相当于主题，改了肯定要重新执行，其他的诸如hexo,hugo之类也是如此😅

**Comment by real-jiakai** [comment]
下载了更新的src目录，覆盖了本地的src目录，接着执行`cargo build --release`，将target/release文件夹里面的blog-cli.exe拖到项目的根目录，生成的public文件夹依然没有成功复制image文件夹以及assets文件夹至public文件夹中。

**Comment by real-jiakai** [comment]
我没学过rust语言，大哥，你可以再去改一改复制文件的代码。更新了，我再试试。
还有一个建议，就是在README里面略微补充一些windows系统下的操作说明。
windows操作说明：
+ 去rust官网下载rustup-init.exe
+ 双击rustup-init.exe
+ 输入1，下载rust语言需要的c++支持
+ 输入1，安装rust语言【更改安装目录请自行查阅】
+ 接着克隆本项目，依据README中的提示修改内容【新建image文件夹，在image文件夹下新建不同类别的文件夹，如旅行，生活等，修改config.json等】
+ 在项目根目录下打开终端，执行`cargo build --release`，生成target文件夹
+ 将target/release文件夹下的blog-cli.exe拖到项目根目录下
+ 双击blog-cli.exe，生成public文件夹
+ 点击public文件夹，目录结构一般如下：
.
├── assets(静态资源文件)
├── image(图片资源文件)
├── 旅行(图片类别名1)
├── 生活(图片类别名2)
└── index.html(主页)
+ 将代码上传到github等代码托管平台
+ 在vercel、netlify等PaaS平台导入仓库代码
+ 选择根目录为public文件夹

**Comment by real-jiakai** [comment]
等大哥修改完代码，我这边验证成功了，我可以在本issue中提交我电脑上生成的blog-cli.exe文件。
你可以加到项目中，这样子可以方便后来者。因为别人为了这个项目下载rust，需要下载一堆c++支持，这些支持还无法选择安装路径，只能往C盘里面怼，这很不友好。

**Comment by doom40k** [comment]
我在测试用GitHub Action 自动打包多环境

**Comment by real-jiakai** [comment]
用github action更方便，直接就生成public文件夹了，接着用github page部署也行。
